import javax.swing.JOptionPane;

public class EverythingIsAwesome {
	public static void main(String[] args) {
		String space=JOptionPane.showInputDialog("What is your favorite thing to do?");
		JOptionPane.showMessageDialog(null, "The activity you mentioned IS the best");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
		JOptionPane.showInputDialog("What are you waiting for right now?");
		JOptionPane.showMessageDialog(null, "I am ALSO waiting for half past seven.");
	}

}

